export const UNIT_CELL_SIZE = 1.5;

export const FCC_POINTS: [number, number, number][] = [
  [0, 0, 0],
  [UNIT_CELL_SIZE, 0, 0],
  [0, UNIT_CELL_SIZE, 0],
  [0, 0, UNIT_CELL_SIZE],
  [UNIT_CELL_SIZE, UNIT_CELL_SIZE, 0],
  [UNIT_CELL_SIZE, 0, UNIT_CELL_SIZE],
  [0, UNIT_CELL_SIZE, UNIT_CELL_SIZE],
  [UNIT_CELL_SIZE, UNIT_CELL_SIZE, UNIT_CELL_SIZE],
  [UNIT_CELL_SIZE / 2, UNIT_CELL_SIZE / 2, 0],
  [UNIT_CELL_SIZE / 2, 0, UNIT_CELL_SIZE / 2],
  [0, UNIT_CELL_SIZE / 2, UNIT_CELL_SIZE / 2],
  [UNIT_CELL_SIZE / 2, UNIT_CELL_SIZE, UNIT_CELL_SIZE / 2],
  [UNIT_CELL_SIZE / 2, UNIT_CELL_SIZE / 2, UNIT_CELL_SIZE],
  [UNIT_CELL_SIZE, UNIT_CELL_SIZE / 2, UNIT_CELL_SIZE / 2],
];

export const INTERWEAVING_POINTS: [number, number, number][] = [
  [UNIT_CELL_SIZE / 2, 0, 0],
  [UNIT_CELL_SIZE, UNIT_CELL_SIZE / 2, 0],
  [0, UNIT_CELL_SIZE / 2, 0],
  [UNIT_CELL_SIZE / 2, UNIT_CELL_SIZE, 0],
  [UNIT_CELL_SIZE, 0, UNIT_CELL_SIZE / 2],
  [0, 0, UNIT_CELL_SIZE / 2],
  [0, UNIT_CELL_SIZE, UNIT_CELL_SIZE / 2],
  [UNIT_CELL_SIZE, UNIT_CELL_SIZE, UNIT_CELL_SIZE / 2],
  [UNIT_CELL_SIZE / 2, UNIT_CELL_SIZE / 2, UNIT_CELL_SIZE / 2],
  [UNIT_CELL_SIZE / 2, 0, UNIT_CELL_SIZE],
  [UNIT_CELL_SIZE, UNIT_CELL_SIZE / 2, UNIT_CELL_SIZE],
  [0, UNIT_CELL_SIZE / 2, UNIT_CELL_SIZE],
  [UNIT_CELL_SIZE / 2, UNIT_CELL_SIZE, UNIT_CELL_SIZE],
];
